spring:
  application:
    name: facebook-version2
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/facebook-version2
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

jwt:
  secret: gS10SK2gBgL0gK7KqLf76KzK1gS0Kfg0KDzSg6eeS1SKBfODKg0K1e7zLqK6
logging:
  file:
    name: logs/facebook-version2.log
  level:
    org:
      springframework:
        cache: error
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

server:
  error:
    include-message: always
  port: 3456